// This file is automatically generated. Keep runtime guards lightweight.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SAFE_SUPABASE_PUBLISHABLE_KEY, SAFE_SUPABASE_URL } from '@/lib/env';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SAFE_SUPABASE_URL, SAFE_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
