// Pealim source map for automated import.
//
// This file intentionally stores only source-level metadata. Full conjugation
// cards must be generated by scripts/pealim-import.mjs and then validated.

export type PealimSourceEntry = {
  rank: number;
  infinitive: string;
  translation_ru: string;
  pealimUrl: string;
  tier: "top_conversational_350" | "mid_frequency_350";
  difficulty: "easy" | "medium" | "hard";
};

export const PEALIM_TOP350_SOURCE_MAP: PealimSourceEntry[] = [
  { rank: 34, infinitive: "למצוא", translation_ru: "находить", pealimUrl: "https://www.pealim.com/ru/dict/1083-limtzo/", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 35, infinitive: "להרגיש", translation_ru: "чувствовать; чувствовать себя", pealimUrl: "https://www.pealim.com/ru/dict/1993-lehargish/", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 36, infinitive: "להכיר", translation_ru: "знать; быть знакомым; узнавать", pealimUrl: "https://www.pealim.com/ru/search/?q=%D7%9C%D7%94%D7%9B%D7%99%D7%A8", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 37, infinitive: "להתחיל", translation_ru: "начинать", pealimUrl: "https://www.pealim.com/ru/dict/2359-lehatchil/", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 38, infinitive: "להמשיך", translation_ru: "продолжать", pealimUrl: "https://www.pealim.com/ru/dict/1110-lehamshich/", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 39, infinitive: "להפסיק", translation_ru: "прекращать; переставать", pealimUrl: "https://www.pealim.com/ru/search/?q=%D7%9C%D7%94%D7%A4%D7%A1%D7%99%D7%A7", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 40, infinitive: "לקנות", translation_ru: "покупать; приобретать", pealimUrl: "https://www.pealim.com/ru/dict/1913-liknot/", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 41, infinitive: "לשלם", translation_ru: "платить", pealimUrl: "https://www.pealim.com/ru/dict/2232-leshalem/", tier: "top_conversational_350", difficulty: "easy" },
  { rank: 42, infinitive: "לבשל", translation_ru: "варить; готовить", pealimUrl: "https://www.pealim.com/ru/dict/273-levashel/", tier: "top_conversational_350", difficulty: "easy" },
  { rank: 43, infinitive: "לנקות", translation_ru: "чистить; убирать", pealimUrl: "https://www.pealim.com/ru/dict/1252-lenakot/", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 44, infinitive: "לתקן", translation_ru: "чинить; исправлять", pealimUrl: "https://www.pealim.com/ru/dict/2392-letaken/", tier: "top_conversational_350", difficulty: "easy" },
  { rank: 45, infinitive: "לסדר", translation_ru: "упорядочивать; налаживать", pealimUrl: "https://www.pealim.com/ru/search/?q=%D7%9C%D7%A1%D7%93%D7%A8", tier: "top_conversational_350", difficulty: "easy" },
  { rank: 46, infinitive: "להתקשר", translation_ru: "звонить; связываться", pealimUrl: "https://www.pealim.com/ru/dict/1971-lehitkasher/", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 47, infinitive: "להתכתב", translation_ru: "переписываться", pealimUrl: "https://www.pealim.com/ru/search/?q=%D7%9C%D7%94%D7%AA%D7%9B%D7%AA%D7%91", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 48, infinitive: "להתאמן", translation_ru: "тренироваться", pealimUrl: "https://www.pealim.com/ru/search/?q=%D7%9C%D7%94%D7%AA%D7%90%D7%9E%D7%9F", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 49, infinitive: "להתעניין", translation_ru: "интересоваться", pealimUrl: "https://www.pealim.com/ru/search/?q=%D7%9C%D7%94%D7%AA%D7%A2%D7%A0%D7%99%D7%99%D7%9F", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 50, infinitive: "להסתדר", translation_ru: "справляться; ладить; устраиваться", pealimUrl: "https://www.pealim.com/ru/search/?q=%D7%9C%D7%94%D7%A1%D7%AA%D7%93%D7%A8", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 51, infinitive: "להתכונן", translation_ru: "готовиться", pealimUrl: "https://www.pealim.com/ru/search/?q=%D7%9C%D7%94%D7%AA%D7%9B%D7%95%D7%A0%D7%9F", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 52, infinitive: "לעלות", translation_ru: "подниматься; стоить", pealimUrl: "https://www.pealim.com/ru/search/?q=%D7%9C%D7%A2%D7%9C%D7%95%D7%AA", tier: "top_conversational_350", difficulty: "medium" },
  { rank: 53, infinitive: "לרדת", translation_ru: "спускаться; снижаться", pealimUrl: "https://www.pealim.com/ru/search/?q=%D7%9C%D7%A8%D7%93%D7%AA", tier: "top_conversational_350", difficulty: "medium" },
];
